# Mypy check
#
# Use Mypy project (github.com/python/mypy) to perform static type check ing of your code.
# Play around a little bit with Mypy, go through results and reports generated by running the mypy,
# perform refactoring based on the mentioned results.

# (venv) yurii.kotliar@UPS-Kotliar1 homework % mypy task1.py
# Success: no issues found in 1 source file
